# Generated by Django 3.2.9 on 2021-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
